edit_uri: blob/master/docs/
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Introduction: README.md
  - ...
plugins:
  - awesome-pages:
  - search:
  - section-index:
repo_url: https://github.com/aserowy/thebook/
site_author: Alexander Serowy
site_name: thebook
theme:
  name: material
  features:
    - navigation.instant
