edit_uri: blob/master/docs/
nav:
  - Introduction: README.md
  - ...
  - links.md
plugins:
  - awesome-pages:
  - search:
  - tags:
repo_url: https://github.com/aserowy/thebook/
site_author: Alexander Serowy
site_name: thebook
theme: material