name: deploy master
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          GITHUB_ACTOR: aserowy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
