name: build master
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: actions/mkdocs-ghpages-docker-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
